### ISSUE TITLE
Questions with configuration

### ISSUE THREAD

**Issue by hideharu1977** [Adobe-Marketing-Cloud/target-atjs-extensions#1]
Hi, 

Can you please explain or direct me to a document that explains how to do the item below?

> Integration Instructions:
> 
> **Use at.js without the auto-created mbox**

**Comment by dwright-adobe** [comment]
Hi @hideharu1977 ,
With the April release, you will be able to toggle the "auto-created mbox" from the Target UI before you download at.js.  For the time being, in order to turn off the auto-created mbox you should:
1. Download at.js via the API
2. Look for the section "globalMboxAutoCreate:true" and change this to "globalMboxAutoCreate:false"

Please re-open this issue if that doesn't work for you.
